src/Entity/Action.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Action\AdminActionDTO;
use App\Repository\ActionRepository;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActionRepository::class)]
class Action implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?string $airTableId = null;

    #[ORM\Column()]
    private ?string $title = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?string $pictureFilename = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactFirstName = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactLastName = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactRole = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactPhoneNumber = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactEmail = null;

    #[ORM\ManyToOne(inversedBy: 'actions')]
    private ?Partner $partner = null;

    #[ORM\OneToMany(mappedBy: 'action', targetEntity: Occurrence::class, orphanRemoval: true)]
    private Collection $occurrences;

    #[ORM\ManyToOne(inversedBy: 'action')]
    private ?Thematic $thematic = null;

    public function __construct()
    {
        $this->occurrences = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->title;
    }

    public static function create(AdminActionDTO $actionDTO): Action
    {
        $action = new self();

        $action->title = $actionDTO->getTitle();
        $action->description = $actionDTO->getDescription();
        $action->contactFirstName = $actionDTO->getContactFirstName();
        $action->contactLastName = $actionDTO->getContactLastName();
        $action->contactRole = $actionDTO->getContactRole();
        $action->contactPhoneNumber = $actionDTO->getContactPhoneNumber();
        $action->contactEmail = $actionDTO->getContactEmail();
        $action->partner = $actionDTO->getPartner();
        $action->thematic = $actionDTO->getThematic();
        $action->airTableId = $actionDTO->getAirtableId();

        return $action;
    }

    public function edit(AdminActionDTO $actionDTO): void
    {
        $this->title = $actionDTO->getTitle();
        $this->description = $actionDTO->getDescription();
        $this->contactFirstName = $actionDTO->getContactFirstName();
        $this->contactLastName = $actionDTO->getContactLastName();
        $this->contactRole = $actionDTO->getContactRole();
        $this->contactPhoneNumber = $actionDTO->getContactPhoneNumber();
        $this->contactEmail = $actionDTO->getContactEmail();
        $this->partner = $actionDTO->getPartner();
        $this->thematic = $actionDTO->getThematic();
    }

    public function setPictureFilename(?string $pictureFilename): void
    {
        $this->pictureFilename = $pictureFilename;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAirTableId(): ?string
    {
        return $this->airTableId;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getPictureFilename(): ?string
    {
        return $this->pictureFilename;
    }

    public function getPicturePath()
    {
        return UploaderHelper::ACTION_PICTURE.'/'.$this->getPictureFilename();
    }

    public function getContactFirstName(): ?string
    {
        return $this->contactFirstName;
    }

    public function getContactLastName(): ?string
    {
        return $this->contactLastName;
    }

    public function getContactRole(): ?string
    {
        return $this->contactRole;
    }

    public function getContactPhoneNumber(): ?string
    {
        return $this->contactPhoneNumber;
    }

    public function getContactEmail(): ?string
    {
        return $this->contactEmail;
    }

    public function getPartner(): ?Partner
    {
        return $this->partner;
    }

    public function setPartner(?Partner $partner): self
    {
        $this->partner = $partner;

        return $this;
    }

    /**
     * @return Collection|Occurrence[]
     */
    public function getOccurrences(): Collection
    {
        return $this->occurrences;
    }

    public function addOccurrence(Occurrence $occurrence): self
    {
        if (!$this->occurrences->contains($occurrence)) {
            $this->occurrences[] = $occurrence;
            $occurrence->setAction($this);
        }

        return $this;
    }

    public function removeOccurrence(Occurrence $occurrence): self
    {
        if ($this->occurrences->contains($occurrence)) {
            $this->occurrences->removeElement($occurrence);
            // set the owning side to null (unless already changed)
            if ($occurrence->getAction() === $this) {
                $occurrence->setAction(null);
            }
        }

        return $this;
    }

    public function getThematic(): ?Thematic
    {
        return $this->thematic;
    }

    public function setThematic(?Thematic $thematic): self
    {
        $this->thematic = $thematic;

        return $this;
    }
}

src/Entity/Occurrence.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Occurrence\AdminOccurrenceDTO;
use App\Repository\OccurrenceRepository;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OccurrenceRepository::class)]
class Occurrence implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column()]
    private ?int $totalNeededVolunteers = null;

    #[ORM\Column()]
    private ?int $reservedRegistrations = null;

    #[ORM\Column()]
    private ?int $childrenMinimumAge = null;

    #[ORM\Column()]
    private ?int $childrenMaximumNumber = null;

    #[ORM\Column(type: 'carbon_immutable')]
    private ?CarbonImmutable $startAt = null;

    #[ORM\Column(type: 'carbon_immutable')]
    private ?CarbonImmutable $endsAt = null;

    #[ORM\Column(type: 'carbon_immutable', nullable: true)]
    private ?CarbonImmutable $registerClosedAt = null;

    #[ORM\Column(type: 'carbon_immutable', nullable: true)]
    private ?CarbonImmutable $publishedAt = null;

    #[ORM\Column()]
    private bool $publishable = false;

    #[ORM\Column()]
    private bool $cancelled = false;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'occurrences')]
    private $referrers;

    #[ORM\ManyToOne(inversedBy: 'occurrences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Action $action = null;

    #[ORM\OneToMany(mappedBy: 'occurrence', targetEntity: Registration::class, orphanRemoval: true)]
    private Collection $registrations;

    #[ORM\ManyToOne()]
    #[ORM\JoinColumn(nullable: true)]
    private ?Address $address = null;

    public function __construct()
    {
        $this->referrers = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->startAt->format('d-M H:i').' - '.$this->action->getTitle();
    }

    public function isOpen(): bool
    {
        if (
            $this->isPublishable()
            && ($this->registerClosedAt > Carbon::now())
            && ($this->getRemainingNeededVolunteers() > 0)
            && (!$this->isCancelled())
        ) {
            return true;
        }

        return false;
    }

    public static function create(AdminOccurrenceDTO $occurrenceDTO, Address $address): Occurrence
    {
        $occurrence = new self();

        $occurrence->totalNeededVolunteers = $occurrenceDTO->getTotalNeededVolunteers();
        $occurrence->reservedRegistrations = $occurrenceDTO->getReservedRegistrations();
        $occurrence->childrenMinimumAge = $occurrenceDTO->getChildrenMinimumAge();
        $occurrence->childrenMaximumNumber = $occurrenceDTO->getChildrenMaximumNumber();
        $occurrence->startAt = $occurrenceDTO->getStartAt();
        $occurrence->endsAt = $occurrenceDTO->getEndsAt();
        $occurrence->registerClosedAt = $occurrenceDTO->getRegisterClosedAt();
        $occurrence->publishedAt = $occurrenceDTO->getPublishedAt();
        $occurrence->publishable = $occurrenceDTO->isPublishable();
        $occurrence->referrers = $occurrenceDTO->getReferrers();
        $occurrence->action = $occurrenceDTO->getAction();
        $occurrence->address = $address;

        return $occurrence;
    }

    public function edit(AdminOccurrenceDTO $occurrenceDTO): void
    {
        $this->totalNeededVolunteers = $occurrenceDTO->getTotalNeededVolunteers();
        $this->reservedRegistrations = $occurrenceDTO->getReservedRegistrations();
        $this->childrenMinimumAge = $occurrenceDTO->getChildrenMinimumAge();
        $this->childrenMaximumNumber = $occurrenceDTO->getChildrenMaximumNumber();
        $this->startAt = $occurrenceDTO->getStartAt();
        $this->endsAt = $occurrenceDTO->getEndsAt();
        $this->registerClosedAt = $occurrenceDTO->getRegisterClosedAt();
        $this->publishedAt = $occurrenceDTO->getPublishedAt();
        $this->publishable = $occurrenceDTO->isPublishable();
        $this->referrers = $occurrenceDTO->getReferrers();
        $this->action = $occurrenceDTO->getAction();
    }

    public function cancel(): void
    {
        $this->cancelled = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTotalNeededVolunteers(): ?int
    {
        return $this->totalNeededVolunteers;
    }

    public function getReservedRegistrations(): ?int
    {
        return $this->reservedRegistrations;
    }

    public function getRemainingNeededVolunteers(): ?int
    {
        $realPlacesWithoutRegistrations = $this->totalNeededVolunteers - $this->reservedRegistrations;

        $registrationWithChildren = 0;
        foreach ($this->registrations as $registration) {
            if (!$registration->isCancelled()) {
                $registrationWithChildren += 1 + $registration->getChildrenNumber();
            }
        }

        return $realPlacesWithoutRegistrations - $registrationWithChildren;
    }

    public function getChildrenMinimumAge(): ?int
    {
        return $this->childrenMinimumAge;
    }

    public function getChildrenMaximumNumber(): ?int
    {
        return $this->childrenMaximumNumber;
    }

    public function getRemainingChildrenPlaces(): ?int
    {
        $childPlaces = 0;
        foreach ($this->registrations as $registration) {
            if (!$registration->isCancelled()) {
                $childPlaces = +$registration->getChildrenNumber();
            }
        }

        return $this->getChildrenMaximumNumber() - $childPlaces;
    }

    public function getStartAt(): ?CarbonImmutable
    {
        return $this->startAt;
    }

    public function getEndsAt(): ?CarbonImmutable
    {
        return $this->endsAt;
    }

    public function getDuration(): string
    {
        return $this->endsAt->locale('fr_FR')->diffForHumans($this->startAt, true, true, 2);
    }

    public function getRegisterClosedAt(): ?CarbonImmutable
    {
        return $this->registerClosedAt;
    }

    public function getPublishedAt(): ?CarbonImmutable
    {
        return $this->publishedAt;
    }

    public function isPublishable(): bool
    {
        if ($this->referrers->isEmpty()) {
            return false;
        }

        return $this->publishable;
    }

    public function isCancelled(): bool
    {
        return $this->cancelled;
    }

    /**
     * @return Collection|User[]
     */
    public function getReferrers(): Collection
    {
        return $this->referrers;
    }

    public function addReferrer(User $referrer): self
    {
        if (!$this->referrers->contains($referrer)) {
            $this->referrers[] = $referrer;
        }

        return $this;
    }

    public function removeReferrer(User $referrer): self
    {
        if ($this->referrers->contains($referrer)) {
            $this->referrers->removeElement($referrer);
        }

        return $this;
    }

    public function getAction(): ?Action
    {
        return $this->action;
    }

    public function setAction(?Action $action): self
    {
        $this->action = $action;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setOccurrence($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getOccurrence() === $this) {
                $registration->setOccurrence(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }
}

src/Entity/Registration.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Registration\AdminRegistrationDTO;
use App\Model\DTO\Calendar\Registration\RegistrationDTO;
use App\Repository\RegistrationRepository;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: RegistrationRepository::class)]
class Registration
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'registrations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Occurrence $occurrence = null;

    #[ORM\ManyToOne(inversedBy: 'registrations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $volunteer = null;

    #[ORM\Column(nullable: true)]
    private ?int $childrenNumber = null;

    #[ORM\Column()]
    private bool $waitListed = false;

    #[ORM\Column()]
    private bool $cancelled = false;

    #[ORM\Column(nullable: true)]
    private ?CarbonImmutable $cancelledAt = null;

    public function getStatus(): string
    {
        if ($this->cancelled) {
            return 'cancelled';
        }
        if ($this->waitListed) {
            return 'waitListed';
        }
        if ($this->occurrence->getEndsAt() < Carbon::now()) {
            return 'completed';
        }

        return 'confirmed';
    }

    public static function create(RegistrationDTO $registrationDTO, Occurrence $occurrence, User $volunteer): Registration
    {
        $registration = new self();

        $registration->volunteer = $volunteer;
        $registration->occurrence = $occurrence;
        $registration->childrenNumber = $registrationDTO->getChildrenNumber();

        return $registration;
    }

    public function edit(RegistrationDTO $registrationDTO): void
    {
        $this->childrenNumber = $registrationDTO->getChildrenNumber();
    }

    public static function createFromAdmin(AdminRegistrationDTO $registrationDTO): Registration
    {
        $registration = new self();

        $registration->volunteer = $registrationDTO->getVolunteer();
        $registration->occurrence = $registrationDTO->getOccurrence();

        $registration->childrenNumber = $registrationDTO->getChildrenNumber();

        return $registration;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOccurrence(): ?Occurrence
    {
        return $this->occurrence;
    }

    public function setOccurrence(?Occurrence $occurrence): self
    {
        $this->occurrence = $occurrence;

        return $this;
    }

    public function getVolunteer(): ?User
    {
        return $this->volunteer;
    }

    public function getChildrenNumber(): int
    {
        if (!$this->childrenNumber) {
            return 0;
        }

        return $this->childrenNumber;
    }

    public function isWaitListed(): bool
    {
        return $this->waitListed;
    }

    public function isCancelled(): ?bool
    {
        return $this->cancelled;
    }

    public function cancel(): void
    {
        if ($this->occurrence->getEndsAt() < Carbon::now()) {
            return;
        }
        $this->cancelled = true;
        $this->cancelledAt = CarbonImmutable::now();
    }

    public function unCancel(): void
    {
        $this->cancelled = false;
    }

    public function getCancelledAt(): ?CarbonImmutable
    {
        return $this->cancelledAt;
    }

    public function setCancelledAt(?CarbonImmutable $cancelledAt): self
    {
        $this->cancelledAt = $cancelledAt;

        return $this;
    }
}

templates/referrer/occurrence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/referrer/occurrence/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row mt-5">
            <div class="table-responsive">
                <div class="col my-3">
                    <form>
                        <div class="input-group custom-search-form">
                            <input
                                    type="text"
                                    name="search"
                                    class="form-control"
                                    placeholder="{{ 'index.search.placeholder'|trans({}, 'admin-action') }}"
                                    value="{{ app.request.query.get('search') }}"
                            >
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"></button>
                            </div>
                        </div>
                    </form>
                    <a class="btn btn-primary little-btn" href="{{ path('referrer_occurrence_index_without_referrer') }}">{{ 'index.without_referrer'|trans({}, 'admin-action') }}</a>
                    <a class="btn btn-primary little-btn" href="{{ path('referrer_occurrence_index') }}">{{ 'index.mine'|trans({}, 'admin-action') }}</a>
                </div>
                <table class="table">
                    <thead>
                    <tr>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.partner'|trans({}, 'admin-occurrence'), 'partner.name') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.action'|trans({}, 'admin-occurrence'), 'action.title') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.date'|trans({}, 'admin-occurrence'), 'occurrence.startAt') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.volunteers_number'|trans({}, 'admin-occurrence'), 'occurrence.totalNeededVolunteers') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.children_age'|trans({}, 'admin-occurrence'), 'occurrence.childrenMinimumAge') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.children_number'|trans({}, 'admin-occurrence'), 'occurrence.childrenMaximumNumber') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.register_closed_at'|trans({}, 'admin-occurrence'), 'occurrence.registerClosedAt') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.published_at'|trans({}, 'admin-occurrence'), 'occurrence.publishedAt') }}</th>
                        <th>{{ knp_pagination_sortable(occurrences, 'index.publishable'|trans({}, 'admin-occurrence'), 'occurrence.publishable') }}</th>
                        <th>{{ 'index.actions.title'|trans({}, 'admin-occurrence') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for occurrence in occurrences %}
                        <tr>
                            <td>{{ occurrence.action.partner.name }}</td>
                            <td>{{ occurrence.action.title }}</td>
                            <td>{{ occurrence.startAt|format_date('short') }} {{ occurrence.startAt|format_time('short') }}-{{ occurrence.endsAt|format_time('short') }}</td>
                            <td>{{ occurrence.totalNeededVolunteers - occurrence.remainingNeededVolunteers}} / {{ occurrence.totalNeededVolunteers }}</td>
                            <td>{{ occurrence.childrenMinimumAge }} ans</td>
                            <td>{{ occurrence.childrenMaximumNumber - occurrence.remainingChildrenPlaces }} / {{ occurrence.childrenMaximumNumber }}</td>
                            <td>{{ occurrence.registerClosedAt|format_datetime('short') }}</td>
                            <td>{{ occurrence.publishedAt|format_datetime('short') }}</td>
                            <td>{{ occurrence.publishable ? 'Yes' : 'No' }}</td>
                            <td>
                                <a href="{{ path('referrer_occurrence_show', {'id': occurrence.id}) }}">{{ 'index.actions.show'|trans({}, 'admin-occurrence') }}</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="11">{{ 'index.no_records'|trans({}, 'admin-occurrence') }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
        <div class="row justify-content-center mt-5">
            {{ knp_pagination_render(occurrences) }}
        </div>
    </div>
{% endblock %}

templates/referrer/occurrence/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block body %}
    <div class="container mb-5">
        <h2 class="text-center my-5">{{ occurrence.action.title|upper }}</h2>
        <div class="row justify-content-center mt-5">
            <div class="col-lg-7">
                <img class="img-fluid rounded mb-5 card-img-top"
                     src="{{ occurrence.action.picturePath|imagine_filter('squared_thumbnail_large') }}"
                     alt="...">
            </div>
            <div class="col-lg-5">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>{{ 'show.date.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ occurrence.startAt|format_date('full')|capitalize }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.schedule.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.schedule.value'|trans({
                                    '%start_time%':occurrence.startAt|date('H:i'),
                                    '%end_time%':occurrence.endsAt|date('H:i'),
                                    '%duration%':occurrence.duration,
                                }, 'occurrence') }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.address.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.address.line_1'|trans({
                                    '%street_number%':occurrence.address.streetNumber,
                                    '%route%':occurrence.address.route,
                                }, 'occurrence') }}<br>
                                {{ 'show.address.line_2'|trans({
                                    '%postal_code%':occurrence.address.postalCode,
                                    '%locality%':occurrence.address.locality|upper,
                                }, 'occurrence') }}
                            </td>
                        </tr>
                        <tr>
                            <th>{{ 'show.referrer.title'|trans({}, 'occurrence') }}</th>
                            <td>
                                <table class="table-borderless table-sm">
                                    {% for referrer in occurrence.referrers %}
                                        <tr>
                                            <th>
                                                <a href="{{ path('user_public_show', {'id': referrer.id}) }}">{{ referrer.firstName }} {{ referrer.lastName }}</a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <th>{{ 'show.partner.title'|trans({}, 'occurrence') }}</th>
                            <td>
                                <table class="table-borderless table-sm">
                                    <tr>
                                        <td>
                                            {{ occurrence.action.contactFirstName }}
                                            {{ occurrence.action.contactLastName }}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>{{ occurrence.action.contactPhoneNumber }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ occurrence.action.contactEmail }}</td>
                                    </tr>
                                </table>
                            </td>

                        </tr>
                        <tr>
                            <th>{{ 'show.total_places.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.total_places.value'|trans({
                                    '%total_needed_vol%': occurrence.totalNeededVolunteers
                                }, 'occurrence') }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.remaining_places.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.remaining_places.value'|trans({
                                    '%remaining_places%': occurrence.remainingNeededVolunteers
                                }, 'occurrence') }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.registration_closing.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ occurrence.registerClosedAt|format_datetime('medium')|capitalize }}</td>
                        </tr>
                        </tbody>
                    </table>

                    {% if occurrence.childrenMaximumNumber > 0 %}
                        <div class="card text-white bg-secondary text-center mb-4 ml-lg-5 mr-lg-5">
                            <div class="card-body">
                                <h5 class="card-title mb-2 ">{{ 'show.children.title'|trans({}, 'occurrence') }}</h5>
                                <p class="card-text">{{ 'show.children.description'|trans({
                                        '%children_age%':occurrence.childrenMinimumAge,
                                        '%max_children%': occurrence.childrenMaximumNumber
                                    }, 'occurrence') }}</p>
                                <p class="card-text">{{ 'show.children.value'|trans({'%children_remaining_places%': occurrence.remainingChildrenPlaces,}, 'occurrence') }}</p>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-6">
                <table class="table table-responsive table-hover">
                    <tbody>
                    <tr>
                        <th>{{ 'show.user.name'|trans({}, 'referrer-occurrence') }}</th>
                        <th>{{ 'show.user.phone_number'|trans({}, 'referrer-occurrence') }}</th>
                        <th>{{ 'show.user.email'|trans({}, 'referrer-occurrence') }}</th>
                        <th>{{ 'show.user.children_number'|trans({}, 'referrer-occurrence') }}</th>
                    </tr>
                    {% for registration in occurrence.registrations %}
                        {% if registration.status == 'confirmed' %}
                            <tr>
                                <td>
                                    <a href="{{ path('user_public_show', {'id': registration.volunteer.id}) }}">
                                        {{ registration.volunteer.firstName }} {{ registration.volunteer.lastName }}
                                    </a>
                                </td>
                                <td>{{ registration.volunteer.phoneNumber }}</td>
                                <td>{{ registration.volunteer.email }}</td>
                                <td>{{ registration.childrenNumber }}</td>
                            </tr>
                        {% endif %}
                    {% else %}
                        <tr>
                            <td>{{ 'show.user.no_records'|trans({}, 'referrer-occurrence') }}
                            <td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-6">
                <p>{{ occurrence.action.description }}</p>
                <h2>{{ occurrence.action.partner.name }}</h2>
                <p>{{ occurrence.action.partner.description }}</p>
            </div>
        </div>
    </div>
{% endblock %}