src/Entity/Action.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Action\AdminActionDTO;
use App\Repository\ActionRepository;
use App\Service\UploaderHelper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActionRepository::class)]
class Action implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?string $airTableId = null;

    #[ORM\Column()]
    private ?string $title = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?string $pictureFilename = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactFirstName = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactLastName = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactRole = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactPhoneNumber = null;

    #[ORM\Column(nullable: true)]
    private ?string $contactEmail = null;

    #[ORM\ManyToOne(inversedBy: 'actions')]
    private ?Partner $partner = null;

    #[ORM\OneToMany(mappedBy: 'action', targetEntity: Occurrence::class, orphanRemoval: true)]
    private Collection $occurrences;

    #[ORM\ManyToOne(inversedBy: 'action')]
    private ?Thematic $thematic = null;

    public function __construct()
    {
        $this->occurrences = new ArrayCollection();
    }

    public function __toString(): string
    {
        return (string) $this->title;
    }

    public static function create(AdminActionDTO $actionDTO): Action
    {
        $action = new self();

        $action->title = $actionDTO->getTitle();
        $action->description = $actionDTO->getDescription();
        $action->contactFirstName = $actionDTO->getContactFirstName();
        $action->contactLastName = $actionDTO->getContactLastName();
        $action->contactRole = $actionDTO->getContactRole();
        $action->contactPhoneNumber = $actionDTO->getContactPhoneNumber();
        $action->contactEmail = $actionDTO->getContactEmail();
        $action->partner = $actionDTO->getPartner();
        $action->thematic = $actionDTO->getThematic();
        $action->airTableId = $actionDTO->getAirtableId();

        return $action;
    }

    public function edit(AdminActionDTO $actionDTO): void
    {
        $this->title = $actionDTO->getTitle();
        $this->description = $actionDTO->getDescription();
        $this->contactFirstName = $actionDTO->getContactFirstName();
        $this->contactLastName = $actionDTO->getContactLastName();
        $this->contactRole = $actionDTO->getContactRole();
        $this->contactPhoneNumber = $actionDTO->getContactPhoneNumber();
        $this->contactEmail = $actionDTO->getContactEmail();
        $this->partner = $actionDTO->getPartner();
        $this->thematic = $actionDTO->getThematic();
    }

    public function setPictureFilename(?string $pictureFilename): void
    {
        $this->pictureFilename = $pictureFilename;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAirTableId(): ?string
    {
        return $this->airTableId;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getPictureFilename(): ?string
    {
        return $this->pictureFilename;
    }

    public function getPicturePath()
    {
        return UploaderHelper::ACTION_PICTURE.'/'.$this->getPictureFilename();
    }

    public function getContactFirstName(): ?string
    {
        return $this->contactFirstName;
    }

    public function getContactLastName(): ?string
    {
        return $this->contactLastName;
    }

    public function getContactRole(): ?string
    {
        return $this->contactRole;
    }

    public function getContactPhoneNumber(): ?string
    {
        return $this->contactPhoneNumber;
    }

    public function getContactEmail(): ?string
    {
        return $this->contactEmail;
    }

    public function getPartner(): ?Partner
    {
        return $this->partner;
    }

    public function setPartner(?Partner $partner): self
    {
        $this->partner = $partner;

        return $this;
    }

    /**
     * @return Collection|Occurrence[]
     */
    public function getOccurrences(): Collection
    {
        return $this->occurrences;
    }

    public function addOccurrence(Occurrence $occurrence): self
    {
        if (!$this->occurrences->contains($occurrence)) {
            $this->occurrences[] = $occurrence;
            $occurrence->setAction($this);
        }

        return $this;
    }

    public function removeOccurrence(Occurrence $occurrence): self
    {
        if ($this->occurrences->contains($occurrence)) {
            $this->occurrences->removeElement($occurrence);
            // set the owning side to null (unless already changed)
            if ($occurrence->getAction() === $this) {
                $occurrence->setAction(null);
            }
        }

        return $this;
    }

    public function getThematic(): ?Thematic
    {
        return $this->thematic;
    }

    public function setThematic(?Thematic $thematic): self
    {
        $this->thematic = $thematic;

        return $this;
    }
}

src/Entity/Occurrence.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Occurrence\AdminOccurrenceDTO;
use App\Repository\OccurrenceRepository;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OccurrenceRepository::class)]
class Occurrence implements \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column()]
    private ?int $totalNeededVolunteers = null;

    #[ORM\Column()]
    private ?int $reservedRegistrations = null;

    #[ORM\Column()]
    private ?int $childrenMinimumAge = null;

    #[ORM\Column()]
    private ?int $childrenMaximumNumber = null;

    #[ORM\Column(type: 'carbon_immutable')]
    private ?CarbonImmutable $startAt = null;

    #[ORM\Column(type: 'carbon_immutable')]
    private ?CarbonImmutable $endsAt = null;

    #[ORM\Column(type: 'carbon_immutable', nullable: true)]
    private ?CarbonImmutable $registerClosedAt = null;

    #[ORM\Column(type: 'carbon_immutable', nullable: true)]
    private ?CarbonImmutable $publishedAt = null;

    #[ORM\Column()]
    private bool $publishable = false;

    #[ORM\Column()]
    private bool $cancelled = false;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'occurrences')]
    private $referrers;

    #[ORM\ManyToOne(inversedBy: 'occurrences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Action $action = null;

    #[ORM\OneToMany(mappedBy: 'occurrence', targetEntity: Registration::class, orphanRemoval: true)]
    private Collection $registrations;

    #[ORM\ManyToOne()]
    #[ORM\JoinColumn(nullable: true)]
    private ?Address $address = null;

    public function __construct()
    {
        $this->referrers = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->startAt->format('d-M H:i').' - '.$this->action->getTitle();
    }

    public function isOpen(): bool
    {
        if (
            $this->isPublishable()
            && ($this->registerClosedAt > Carbon::now())
            && ($this->getRemainingNeededVolunteers() > 0)
            && (!$this->isCancelled())
        ) {
            return true;
        }

        return false;
    }

    public static function create(AdminOccurrenceDTO $occurrenceDTO, Address $address): Occurrence
    {
        $occurrence = new self();

        $occurrence->totalNeededVolunteers = $occurrenceDTO->getTotalNeededVolunteers();
        $occurrence->reservedRegistrations = $occurrenceDTO->getReservedRegistrations();
        $occurrence->childrenMinimumAge = $occurrenceDTO->getChildrenMinimumAge();
        $occurrence->childrenMaximumNumber = $occurrenceDTO->getChildrenMaximumNumber();
        $occurrence->startAt = $occurrenceDTO->getStartAt();
        $occurrence->endsAt = $occurrenceDTO->getEndsAt();
        $occurrence->registerClosedAt = $occurrenceDTO->getRegisterClosedAt();
        $occurrence->publishedAt = $occurrenceDTO->getPublishedAt();
        $occurrence->publishable = $occurrenceDTO->isPublishable();
        $occurrence->referrers = $occurrenceDTO->getReferrers();
        $occurrence->action = $occurrenceDTO->getAction();
        $occurrence->address = $address;

        return $occurrence;
    }

    public function edit(AdminOccurrenceDTO $occurrenceDTO): void
    {
        $this->totalNeededVolunteers = $occurrenceDTO->getTotalNeededVolunteers();
        $this->reservedRegistrations = $occurrenceDTO->getReservedRegistrations();
        $this->childrenMinimumAge = $occurrenceDTO->getChildrenMinimumAge();
        $this->childrenMaximumNumber = $occurrenceDTO->getChildrenMaximumNumber();
        $this->startAt = $occurrenceDTO->getStartAt();
        $this->endsAt = $occurrenceDTO->getEndsAt();
        $this->registerClosedAt = $occurrenceDTO->getRegisterClosedAt();
        $this->publishedAt = $occurrenceDTO->getPublishedAt();
        $this->publishable = $occurrenceDTO->isPublishable();
        $this->referrers = $occurrenceDTO->getReferrers();
        $this->action = $occurrenceDTO->getAction();
    }

    public function cancel(): void
    {
        $this->cancelled = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTotalNeededVolunteers(): ?int
    {
        return $this->totalNeededVolunteers;
    }

    public function getReservedRegistrations(): ?int
    {
        return $this->reservedRegistrations;
    }

    public function getRemainingNeededVolunteers(): ?int
    {
        $realPlacesWithoutRegistrations = $this->totalNeededVolunteers - $this->reservedRegistrations;

        $registrationWithChildren = 0;
        foreach ($this->registrations as $registration) {
            if (!$registration->isCancelled()) {
                $registrationWithChildren += 1 + $registration->getChildrenNumber();
            }
        }

        return $realPlacesWithoutRegistrations - $registrationWithChildren;
    }

    public function getChildrenMinimumAge(): ?int
    {
        return $this->childrenMinimumAge;
    }

    public function getChildrenMaximumNumber(): ?int
    {
        return $this->childrenMaximumNumber;
    }

    public function getRemainingChildrenPlaces(): ?int
    {
        $childPlaces = 0;
        foreach ($this->registrations as $registration) {
            if (!$registration->isCancelled()) {
                $childPlaces = +$registration->getChildrenNumber();
            }
        }

        return $this->getChildrenMaximumNumber() - $childPlaces;
    }

    public function getStartAt(): ?CarbonImmutable
    {
        return $this->startAt;
    }

    public function getEndsAt(): ?CarbonImmutable
    {
        return $this->endsAt;
    }

    public function getDuration(): string
    {
        return $this->endsAt->locale('fr_FR')->diffForHumans($this->startAt, true, true, 2);
    }

    public function getRegisterClosedAt(): ?CarbonImmutable
    {
        return $this->registerClosedAt;
    }

    public function getPublishedAt(): ?CarbonImmutable
    {
        return $this->publishedAt;
    }

    public function isPublishable(): bool
    {
        if ($this->referrers->isEmpty()) {
            return false;
        }

        return $this->publishable;
    }

    public function isCancelled(): bool
    {
        return $this->cancelled;
    }

    /**
     * @return Collection|User[]
     */
    public function getReferrers(): Collection
    {
        return $this->referrers;
    }

    public function addReferrer(User $referrer): self
    {
        if (!$this->referrers->contains($referrer)) {
            $this->referrers[] = $referrer;
        }

        return $this;
    }

    public function removeReferrer(User $referrer): self
    {
        if ($this->referrers->contains($referrer)) {
            $this->referrers->removeElement($referrer);
        }

        return $this;
    }

    public function getAction(): ?Action
    {
        return $this->action;
    }

    public function setAction(?Action $action): self
    {
        $this->action = $action;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setOccurrence($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getOccurrence() === $this) {
                $registration->setOccurrence(null);
            }
        }

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }
}

src/Form/Calendar/Occurrence/ContactFormType.php
<?php

namespace App\Form\Calendar\Occurrence;

use App\Model\DTO\Calendar\Occurrence\contactFormDTO;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('message', TextareaType::class, [
                'label' => false,
                'attr' => ['placeholder' => 'form.message.placeholder'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'translation_domain' => 'contact',
            'data_class' => contactFormDTO::class,
        ]);
    }
}

src/Controller/Calendar/OccurrenceController.php
<?php

namespace App\Controller\Calendar;

use App\Entity\Occurrence;
use App\Form\Calendar\Occurrence\ContactFormType;
use App\Model\DTO\Calendar\Occurrence\ContactFormDTO;
use App\Repository\OccurrenceRepository;
use App\Repository\RegistrationRepository;
use App\Service\Mailer\ActionMailer;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/calendrier')]
class OccurrenceController extends AbstractController
{
    final public const MAX_OCCURRENCE_PER_PAGE = 12;

    #[Route(path: '', name: 'occurrence_index', methods: ['GET'])]
    public function index(Request $request, OccurrenceRepository $repository, PaginatorInterface $paginator): Response
    {
        $searchTerm = $request->get('search');
        $queryBuilder = $repository->getWithSearchQueryBuilder($searchTerm);
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            self::MAX_OCCURRENCE_PER_PAGE
        );

        return $this->render('calendar/occurrence/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    #[Route(path: '/occurrence/{id}', name: 'occurrence_show', methods: ['GET', 'POST'])]
    public function show(Request $request, Occurrence $occurrence, ActionMailer $mailer, RegistrationRepository $registrationRepository): Response
    {
        $contactFormDTO = new ContactFormDTO();
        $contactForm = $this->createForm(ContactFormType::class, $contactFormDTO);
        if ($registration = $registrationRepository->findOneBy(['volunteer' => $this->getUser(), 'occurrence' => $occurrence])) {
            $contactForm->handleRequest($request);

            if ($contactForm->isSubmitted() && $contactForm->isValid()) {
                $mailer->sendMessageToReferrer($contactFormDTO, $registration);

                $this->addFlash('success', 'contact-form.success');

                return $this->redirectToRoute('occurrence_show', ['id' => $occurrence->getId()]);
            }
        }

        return $this->render('calendar/occurrence/show.html.twig', [
            'occurrence' => $occurrence,
            'contactForm' => $contactForm->createView(),
        ]);
    }
}

templates/calendar/occurrence/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block body %}
    <div class="container mb-5">
        <h2 class="text-center mt-5">
            {{ occurrence.action.title|upper }}
            {% if occurrence.remainingNeededVolunteers <= 0 %}
                <span class="badge badge-danger">{{ 'registration.full'|trans({}, 'calendar') }}</span>
            {% endif %}
        </h2>
        <div class="row justify-content-center mt-5">

            <div class="col-lg-7">
                <img class="img-fluid rounded mb-5 card-img-top"
                     src="{{ occurrence.action.picturePath|imagine_filter('squared_thumbnail_large') }}"
                     alt="...">
            </div>
            <div class="col-lg-5">
                <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>{{ 'show.date.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ occurrence.startAt|format_date('full')|capitalize }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.schedule.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.schedule.value'|trans({
                                    '%start_time%':occurrence.startAt|date('H:i'),
                                    '%end_time%':occurrence.endsAt|date('H:i'),
                                    '%duration%':occurrence.duration,
                                }, 'occurrence') }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.address.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.address.line_1'|trans({
                                    '%street_number%':occurrence.address.streetNumber,
                                    '%route%':occurrence.address.route,
                                }, 'occurrence') }}<br>
                                {{ 'show.address.line_2'|trans({
                                    '%postal_code%':occurrence.address.postalCode,
                                    '%locality%':occurrence.address.locality|upper,
                                }, 'occurrence') }}
                            </td>
                        </tr>
                        <tr>
                            <th>{{ 'show.referrer.title'|trans({}, 'occurrence') }}</th>
                            <td>
                                <table class="table-borderless table-sm">
                                    {% for referrer in occurrence.referrers %}
                                        <tr>
                                            <th>
                                                <a href="{{ path('user_public_show', {'id': referrer.id}) }}">{{ referrer.firstName }} {{ referrer.lastName }}</a>
                                            </th>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <th>{{ 'show.total_places.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.total_places.value'|trans({
                                    '%total_needed_vol%': occurrence.totalNeededVolunteers
                                }, 'occurrence') }}</td>
                        </tr>
                        <tr>
                            <th>{{ 'show.remaining_places.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ 'show.remaining_places.value'|trans({
                                    '%remaining_places%': occurrence.remainingNeededVolunteers
                                }, 'occurrence') }}</td>
                        </tr>

                        <tr>
                            <th>{{ 'show.registration_closing.title'|trans({}, 'occurrence') }}</th>
                            <td>{{ occurrence.registerClosedAt|format_datetime('medium')|capitalize }}</td>
                        </tr>


                        </tbody>
                    </table>
                    <div class="text-center mb-3">
                        {% if app.user %}
                            {% set registered = false %}
                            {% for registration in app.user.registrations %}
                                {% if registration in occurrence.registrations %}
                                    {% set registered = true %}
                                    {% if registration.occurrence.startAt|date("U") > 'now'|date("U") %}
                                        {% if not registration.cancelled %}
                                            <a href="{{ path('registration_edit',  {'id': registration.id}) }}"
                                               class="btn little-btn btn-primary">{{ 'occurrence.button.edit'|trans({}, 'calendar') }}</a>
                                            {{ include('calendar/registration/_cancel_modal.html.twig') }}
                                        {% else %}
                                            {{ include('calendar/registration/_uncancel_modal.html.twig') }}
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            {% if not registered and occurrence.remainingNeededVolunteers > 0 %}
                                {% if occurrence.open %}
                                    <a href="{{ path('registration_new',  {'id': occurrence.id}) }}"
                                       class="btn little-btn btn-primary">{{ 'occurrence.button.register'|trans({}, 'calendar') }}</a>
                                {% endif %}
                            {% endif %}
                        {% else %}
                            <a href="{{ path('registration_new',  {'id': occurrence.id}) }}"
                               class="btn little-btn btn-primary">{{ 'occurrence.button.register'|trans({}, 'calendar') }}</a>
                        {% endif %}
                    </div>

                    {% if occurrence.childrenMaximumNumber > 0 %}
                        <div class="card text-white bg-secondary text-center mb-4 ml-lg-5 mr-lg-5">
                            <div class="card-body">
                                <h5 class="card-title mb-2 ">{{ 'show.children.title'|trans({}, 'occurrence') }}</h5>
                                <p class="card-text">{{ 'show.children.description'|trans({
                                        '%children_age%':occurrence.childrenMinimumAge,
                                        '%max_children%': occurrence.childrenMaximumNumber
                                    }, 'occurrence') }}</p>
                                <p class="card-text">{{ 'show.children.value'|trans({'%children_remaining_places%': occurrence.remainingChildrenPlaces,}, 'occurrence') }}</p>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>


        <div class="row justify-content-center">
            {% if app.user %}
                {% if registered %}
                    <div class="col-lg-4">
                        <h5>Envoyer un message aux référents de l'action</h5>
                        {{ form_start(contactForm) }}
                        {{ form_row(contactForm.message) }}
                        <div class="form-group text-center mt-lg-5">
                            <button type="submit" id="contact-submit" class="btn btn-block big_block_btn btn-primary">
                                {{ 'form.submit.label'|trans({}, 'contact') }}
                            </button>
                        </div>
                        {{ form_end(contactForm) }}
                    </div>
                {% endif %}
            {% endif %}
            <div class="col-lg-8">
                <p>{{ occurrence.action.description|markdown }}</p>
                <h2>{{ occurrence.action.partner.name }}</h2>
                <p>{{ occurrence.action.partner.description }}</p>
            </div>

        </div>
    </div>
{% endblock %}