src/Entity/Registration.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\Registration\AdminRegistrationDTO;
use App\Model\DTO\Calendar\Registration\RegistrationDTO;
use App\Repository\RegistrationRepository;
use Carbon\Carbon;
use Carbon\CarbonImmutable;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: RegistrationRepository::class)]
class Registration
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'registrations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Occurrence $occurrence = null;

    #[ORM\ManyToOne(inversedBy: 'registrations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $volunteer = null;

    #[ORM\Column(nullable: true)]
    private ?int $childrenNumber = null;

    #[ORM\Column()]
    private bool $waitListed = false;

    #[ORM\Column()]
    private bool $cancelled = false;

    #[ORM\Column(nullable: true)]
    private ?CarbonImmutable $cancelledAt = null;

    public function getStatus(): string
    {
        if ($this->cancelled) {
            return 'cancelled';
        }
        if ($this->waitListed) {
            return 'waitListed';
        }
        if ($this->occurrence->getEndsAt() < Carbon::now()) {
            return 'completed';
        }

        return 'confirmed';
    }

    public static function create(RegistrationDTO $registrationDTO, Occurrence $occurrence, User $volunteer): Registration
    {
        $registration = new self();

        $registration->volunteer = $volunteer;
        $registration->occurrence = $occurrence;
        $registration->childrenNumber = $registrationDTO->getChildrenNumber();

        return $registration;
    }

    public function edit(RegistrationDTO $registrationDTO): void
    {
        $this->childrenNumber = $registrationDTO->getChildrenNumber();
    }

    public static function createFromAdmin(AdminRegistrationDTO $registrationDTO): Registration
    {
        $registration = new self();

        $registration->volunteer = $registrationDTO->getVolunteer();
        $registration->occurrence = $registrationDTO->getOccurrence();

        $registration->childrenNumber = $registrationDTO->getChildrenNumber();

        return $registration;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOccurrence(): ?Occurrence
    {
        return $this->occurrence;
    }

    public function setOccurrence(?Occurrence $occurrence): self
    {
        $this->occurrence = $occurrence;

        return $this;
    }

    public function getVolunteer(): ?User
    {
        return $this->volunteer;
    }

    public function getChildrenNumber(): int
    {
        if (!$this->childrenNumber) {
            return 0;
        }

        return $this->childrenNumber;
    }

    public function isWaitListed(): bool
    {
        return $this->waitListed;
    }

    public function isCancelled(): ?bool
    {
        return $this->cancelled;
    }

    public function cancel(): void
    {
        if ($this->occurrence->getEndsAt() < Carbon::now()) {
            return;
        }
        $this->cancelled = true;
        $this->cancelledAt = CarbonImmutable::now();
    }

    public function unCancel(): void
    {
        $this->cancelled = false;
    }

    public function getCancelledAt(): ?CarbonImmutable
    {
        return $this->cancelledAt;
    }

    public function setCancelledAt(?CarbonImmutable $cancelledAt): self
    {
        $this->cancelledAt = $cancelledAt;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Model\DTO\Admin\User\AbstractUserDTO;
use App\Model\DTO\Admin\User\AdminCreateUserDTO;
use App\Model\DTO\Admin\User\AdminEditUserDTO;
use App\Model\DTO\User\ChangePasswordDTO;
use App\Model\DTO\User\EditUserDTO;
use App\Model\DTO\User\UserRegistrationDTO;
use App\Service\UploaderHelper;
use Carbon\CarbonImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: 'App\Repository\UserRepository')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Stringable
{
    use TimestampableEntity;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[Gedmo\Slug(fields: ['firstName', 'lastName'])]
    #[ORM\Column(length: 100, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $phoneNumber = null;

    #[ORM\Column(type: 'carbon_immutable', length: 180, precision: 1, nullable: true)]
    private ?CarbonImmutable $birthday = null;

    #[ORM\Column(length: 180, nullable: true)]
    private ?string $district = null;

    #[ORM\Column(nullable: true)]
    private ?string $profilePictureFilename = null;

    #[ORM\Column(type: 'carbon_immutable', length: 180, precision: 3, nullable: true)]
    private ?CarbonImmutable $agreedTermsAt = null;

    #[ORM\Column()]
    private bool $imageRightClearance = true;

    #[ORM\Column()]
    private bool $newsletter = true;

    #[ORM\Column()]
    private bool $emailNotification = true;

    #[ORM\Column()]
    private bool $smsNotification = true;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?ParentalConsentFile $parentalConsentFile = null;

    #[ORM\Column()]
    private bool $parentalConsentValid = true;

    #[ORM\Column()]
    private bool $enabled = true;

    #[ORM\Column()]
    private bool $deactivated = false;

    #[ORM\Column(type: 'json')]
    private ?array $roles = [];

    #[ORM\Column(nullable: true)]
    private ?string $password = null;

    #[ORM\Column(type: 'carbon_immutable', length: 180, precision: 1, nullable: true)]
    private ?CarbonImmutable $changedPasswordAt = null;

    private ?string $plainPassword = null;

    #[ORM\ManyToMany(targetEntity: Occurrence::class, mappedBy: 'referrers')]
    private Collection $occurrences;

    #[ORM\OneToMany(mappedBy: 'volunteer', targetEntity: Registration::class)]
    private Collection $registrations;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?ChangeEmailRequest $changeEmailRequest;

    public function __construct()
    {
        $this->occurrences = new ArrayCollection();
        $this->registrations = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->firstName.' '.$this->lastName.' ('.$this->birthday->format('d M Y').')';
    }

    public static function create(UserRegistrationDTO $userDTO): User
    {
        $user = new self();
        $user->email = $userDTO->getEmail();
        $user->plainPassword = $userDTO->getPlainPassword();
        $user->firstName = $userDTO->getFirstName();
        $user->lastName = $userDTO->getLastName();
        $user->phoneNumber = $userDTO->getPhoneNumber();
        $user->birthday = $userDTO->getBirthday();
        $user->district = $userDTO->getDistrict();
        $user->changedPasswordAt = CarbonImmutable::now();
        if ($userDTO->isAgreedTerms()) {
            $user->agreedTermsAt = CarbonImmutable::now();
        }
        if ($userDTO->getBirthday() > new CarbonImmutable('- 18 years')) {
            $user->parentalConsentValid = false;
        }

        return $user;
    }

    public static function createFromAdmin(AdminCreateUserDTO $userDTO): User
    {
        $user = new self();
        $user->email = $userDTO->getEmail();
        $user->plainPassword = 'Ti'.random_int(5, 25).'Kare?';
        $user->firstName = $userDTO->getFirstName();
        $user->lastName = $userDTO->getLastName();
        $user->phoneNumber = $userDTO->getPhoneNumber();
        $user->birthday = $userDTO->getBirthday();
        $user->district = $userDTO->getDistrict();
        $user->roles = $userDTO->getRoles();

        if ($userDTO->getBirthday() > new CarbonImmutable('- 18 years')) {
            $user->parentalConsentValid = false;
        }

        return $user;
    }

    public function edit(AbstractUserDTO $userDTO)
    {
        $this->firstName = $userDTO->getFirstName();
        $this->lastName = $userDTO->getLastName();
        $this->phoneNumber = $userDTO->getPhoneNumber();
        $this->birthday = $userDTO->getBirthday();
        $this->district = $userDTO->getDistrict();

        if ($userDTO instanceof EditUserDTO) {
            $this->imageRightClearance = $userDTO->isImageRightClearance();
            $this->newsletter = $userDTO->isNewsletter();
        }
        if ($userDTO instanceof AdminEditUserDTO) {
            $this->email = $userDTO->getEmail();
            $this->roles = $userDTO->getRoles();
        }
    }

    public static function createFirstAdmin(string $email, string $password): User
    {
        $user = new self();
        $user->email = $email;
        $user->plainPassword = $password;
        $user->roles = ['ROLE_ADMIN'];

        return $user;
    }

    public function changePassword(ChangePasswordDTO $changePasswordDTO): self
    {
        $this->plainPassword = $changePasswordDTO->getPlainPassword();
        $this->changedPasswordAt = CarbonImmutable::now();

        return $this;
    }

    public function disable(): void
    {
        $this->enabled = false;
    }

    public function enable(): void
    {
        $this->enabled = true;
    }

    public function deactivate(): void
    {
        $this->deactivated = true;
    }

    public function reactivate(): void
    {
        $this->deactivated = false;
    }

    public function parentalConsentValidate(): void
    {
        $this->parentalConsentValid = true;
    }

    public function setProfilePictureFilename(?string $profilePictureFilename): void
    {
        $this->profilePictureFilename = $profilePictureFilename;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function getBirthday(): ?CarbonImmutable
    {
        return $this->birthday;
    }

    public function getDistrict(): ?string
    {
        return $this->district;
    }

    public function getProfilePictureFilename(): ?string
    {
        return $this->profilePictureFilename;
    }

    public function getProfilePicturePath()
    {
        return UploaderHelper::PROFILE_PICTURE.'/'.$this->getProfilePictureFilename();
    }

    public function isImageRightClearance(): bool
    {
        return $this->imageRightClearance;
    }

    public function isNewsletter(): bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(bool $newsletter): void
    {
        $this->newsletter = $newsletter;
    }

    public function isEmailNotification(): bool
    {
        return $this->emailNotification;
    }

    public function isSmsNotification(): bool
    {
        return $this->smsNotification;
    }

    public function getParentalConsentFile(): ?ParentalConsentFile
    {
        return $this->parentalConsentFile;
    }

    public function isParentalConsentValid(): bool
    {
        return $this->parentalConsentValid;
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function isDeactivated(): bool
    {
        return $this->deactivated;
    }

src/Controller/Referrer/UserController.php
<?php

namespace App\Controller\Referrer;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route(path: '/referent/utilisateurs')]
class UserController extends AbstractController
{
    public function __construct(private readonly UserRepository $repository)
    {
    }

    #[Route(path: '/{id}', name: 'referrer_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('referrer/user/show.html.twig', [
            'user' => $user,
        ]);
    }
}

src/Controller/User/ChangeEmailController.php
<?php

namespace App\Controller\User;

use App\Entity\ChangeEmailRequest;
use App\Entity\User;
use App\Form\User\ChangeEmailFormType;
use App\Model\DTO\User\ChangeEmailDTO;
use App\Repository\ChangeEmailRequestRepository;
use App\Security\EmailVerifier;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;

#[Route(path: '/modification-email')]
class ChangeEmailController extends AbstractController
{
    public function __construct(private readonly EmailVerifier $emailVerifier, private readonly ChangeEmailRequestRepository $repository)
    {
    }

    #[Route(path: '', name: 'app_change_email_request')]
    public function request(Request $request): Response
    {
        $user = $this->getUser();

        if (!$user instanceof User) {
            return $this->redirectToRoute('homepage');
        }

        if ($changeEmailRequest = $user->getChangeEmailRequest()) {
            $this->repository->remove($changeEmailRequest);
        }
        $changeEmailDTO = new ChangeEmailDTO();
        $form = $this->createForm(ChangeEmailFormType::class, $changeEmailDTO);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $changeEmailRequest = ChangeEmailRequest::create($changeEmailDTO, $user);

            $this->repository->save($changeEmailRequest);

            // generate a signed url and email it to the user
            $this->emailVerifier->sendEmailConfirmation('app_verify_email', $changeEmailRequest);

            $this->addFlash('success', 'user.change_email.success ');

            return $this->redirectToRoute('user_show');
        }

        return $this->render('user/change_email.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route(path: '/verification', name: 'app_verify_email')]
    public function verifyUserEmail(Request $request): Response
    {
        $user = $this->getUser();
        if (!$user instanceof User) {
            return $this->redirectToRoute('homepage');
        }
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        // validate email confirmation link, sets User::isVerified=true and persists
        try {
            $this->emailVerifier->handleEmailConfirmation($request, $user);
        } catch (VerifyEmailExceptionInterface $exception) {
            $this->addFlash('verify_email_error', $exception->getReason());

            return $this->redirectToRoute('user_show');
        }
        // @TODO Change the redirect on success and handle or remove the flash message in your templates
        $this->addFlash('success', 'user.confirm_email.success');

        return $this->redirectToRoute('user_show');
    }
}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary big_btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/change_email.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ 'change_email.browser_tab_title'|trans({'%firstname%': user.firstName}, 'user') }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-lg-center my-5">
            <div class="col-lg-8">
                <h1>{{ 'change_email.title'|trans({}, 'user') }}</h1>

                {{ include('user/_form.html.twig', {'button_label': 'change_email.form.submit'|trans({}, 'user')}) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ 'edit.browser_tab_title'|trans({'%firstname%': user.firstName}, 'user') }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-lg-center my-5">
            <div class="col-lg-8">
                <h1>{{ 'edit.title'|trans({}, 'user') }}</h1>

                {{ include('user/_form.html.twig', {'button_label': 'edit.form.submit'|trans({}, 'user')}) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/parental_consent.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ 'edit.browser_tab_title'|trans({'%firstname%': user.firstName}, 'user') }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-lg-center my-5">
            <div class="col-lg-8">
                <h1>{{ 'parental_consent.title'|trans({}, 'user') }}</h1>

                {{ include('user/_form.html.twig', {'button_label': 'parental_consent.form.submit'|trans({}, 'user')}) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/public_show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ 'show.browser_tab_title'|trans({'%firstname%': user.firstName}, 'user') }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-10">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-lg-4">
                                <img class="img-fluid rounded"
                                     src="{{ user.profilePicturePath|imagine_filter('squared_thumbnail_small') }}"
                                     alt="...">
                            </div>
                            <div class="col-lg-8">
                                <h3 class="card-text">
                                    {{ user.firstname }} {{ user.lastName|upper }}
                                </h3>
                                <p>
                                    {{ 'show.district'|trans({'district': user.district}, 'user') }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                {% if is_granted('ROLE_REFERRER') %}

                    {% if user.birthday.diff.y < 18 %}
                        <div class="card mb-3">
                            <div class="card-body">
                                <div class="row align-items-center">
                                    <div class="col-lg-8">
                                        <h3>{{ 'show.parental_consent.title'|trans({}, 'user') }}</h3>
                                        <p>
                                            {{ 'show.parental_consent.description'|trans({'email': user.email}, 'user') }}
                                        </p>
                                        <p>
                                            {{ 'public_show.parental_consent.status'|trans({
                                                'parental_consent_status': user.parentalConsentValid
                                            }, 'user') }}
                                        </p>
                                    </div>
                                    <div class="col-lg-4">
                                        {% if user.parentalConsentFilename %}

                                            <a class="btn btn-primary little-btn"
                                               href="{{ uploaded_asset(user.parentalConsentPath) }}">
                                                {{ 'show.parental_consent.link'|trans({}, 'user') }}
                                            </a>

                                        {% else %}
                                            <p>{{ 'show.parental_consent.no_file'|trans({}, 'user') }}</p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row align-items-center">
                                <div class="col-lg-12">
                                    <h3>{{ 'show.account.title'|trans({}, 'user') }}</h3>
                                    <p><span class="badge badge-primary mb-1">
                                        {{ 'show.account.image_clearance.title'|trans({}, 'user') }}
                                        <i class="fa fa-camera"></i>
                                    </span>
                                        {{ 'public_show.account.image_clearance.description'|trans({'clearance' : user.imageRightClearance}, 'user') }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'layout/base.html.twig' %}

{% block title %}{{ 'show.browser_tab_title'|trans({'%firstname%': user.firstName}, 'user') }}{% endblock %}

{% block body %}

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-lg-10">
                <div class="text-right">
                    <a class="btn btn-primary little-btn"
                       href="{{ path('user_edit') }}">{{ 'show.edit'|trans({}, 'user') }}</a>
                </div>
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-lg-4">
                                <img class="img-fluid rounded"
                                     src="{{ user.profilePicturePath|imagine_filter('squared_thumbnail_small') }}"
                                     alt="...">
                            </div>
                            <div class="col-lg-8">
                                <h3 class="card-text">
                                    {{ user.firstname }} {{ user.lastName|upper }}
                                </h3>
                                <p>
                                    {{ 'show.birthday'|trans({'birthday': user.birthday|format_date}, 'user') }}
                                </p>
                                <p>
                                    {{ 'show.district'|trans({'district': user.district}, 'user') }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-lg-8">
                                <h3>{{ 'show.contact.title'|trans({}, 'user') }}</h3>
                                <p>
                                    {{ 'show.contact.email'|trans({'email': user.email}, 'user') }}
                                </p>
                                <p>
                                    {{ 'show.contact.phone_number'|trans({'phone_number': user.phoneNumber}, 'user') }}
                                </p>
                            </div>
                            <div class="col-lg-4">
                                <a class="btn btn-primary little-btn" href="{{ path('app_change_email_request') }}">
                                    {{ 'show.contact.email_edit_button'|trans({}, 'user') }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                {% if user.birthday.diff.y < 18 %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row align-items-center">
                                <div class="col-lg-8">
                                    <h3>{{ 'show.parental_consent.title'|trans({}, 'user') }}</h3>
                                    <p>
                                        {{ 'show.parental_consent.description'|trans({'email': user.email}, 'user') }}
                                    </p>
                                    <p>
                                        {{ 'show.parental_consent.status'|trans({'parental_consent_status': user.parentalConsentValid}, 'user') }}
                                    </p>
                                </div>
                                <div class="col-lg-4">
                                    <a class="btn btn-primary little-btn"
                                       href="{{ path('user_upload_parental_consent') }}">
                                        {{ 'show.parental_consent.upload_button'|trans({}, 'user') }}
                                        <span class="fa fa-upload"></span></a>
                                    {% if user.parentalConsentFile %}
                                        {{ user.parentalConsentFile.originalFilename }}
                                        <a class="btn btn-primary little-btn"
                                           href="{{ path('user_download_parental_consent') }}">
                                            {{ 'show.parental_consent.download_button'|trans({}, 'user') }}
                                            <span class="fa fa-download"></span></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}

                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-lg-12">
                                <h3>{{ 'show.account.title'|trans({}, 'user') }}</h3>
                                <p>
                                    {{ 'show.account.created_at'|trans({'created_at': user.createdAt|format_datetime}, 'user') }}
                                </p>
                                <p><span class="badge badge-primary mb-1">
                                        {{ 'show.account.image_clearance.title'|trans({}, 'user') }}
                                        <i class="fa fa-camera"></i>
                                    </span>
                                    {{ 'show.account.image_clearance.description'|trans({'clearance' : user.imageRightClearance}, 'user') }}
                                </p>
                                <p>
                                    <span class="badge badge-primary mb-1">
                                        {{ 'show.account.newsletter.title'|trans({}, 'user') }}
                                        <i class="fa fa-newspaper-o"></i>
                                    </span>
                                    {{ 'show.account.newsletter.description'|trans({'newsletter': user.newsletter}, 'user') }}
                                </p>
                                <p>
                                    <span class="badge badge-primary mb-1">
                                        {{ 'show.account.deletion.title'|trans({}, 'user') }}
                                        <i class="fa fa-ban"></i>
                                    </span>
                                    {{ 'show.account.deletion.description'|trans({'newsletter': user.newsletter}, 'user') }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-lg-8">
                                <h3>{{ 'show.security.title'|trans({}, 'user') }}</h3>
                                <p>
                                    {{ 'show.security.last_password_change'|trans({'pass_changed_at': user.createdAt|format_datetime}, 'user') }}
                                </p>
                            </div>
                            <div class="col-lg-4">
                                <a class="btn btn-primary little-btn" href="{{ path('app_forgot_password_request') }}">
                                    {{ 'show.security.pass_change_button'|trans({}, 'user') }}
                                </a>
                            </div>

                            <div class="col-lg-8">
                                <p>
                                    {{ 'show.deactivate.description'|trans({}, 'user') }}
                                </p>
                            </div>
                            <div class="col-lg-4">
                                <a class="btn btn-primary little-btn" href="{{ path('user_deactivate') }}">
                                    {{ 'show.deactivate.button'|trans({}, 'user') }}
                                </a>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}